services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.1"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1883:1883"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-ce-node
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
    depends_on:
      - postgres
  device_1:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: freertos_mqtt_tago:latest
    container_name: device_1
    environment:
        CLIENT_ID: dev001
        DEVICE_TOKEN: T1_TOKEN
        MQTT_HOST: host.docker.internal
        MQTT_PORT: 1883
        QUEUE_SIZE: 10
        SENSOR_INTERVAL_MS: 5000
        ENABLE_INFOS: 0
    ports:
      - "9091:9090"
    depends_on:
      - postgres
      - thingsboard-ce
  device_2:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: freertos_mqtt_tago:latest
    container_name: device_2
    environment:
        CLIENT_ID: dev002
        DEVICE_TOKEN: T2_TOKEN
        MQTT_HOST: host.docker.internal
        MQTT_PORT: 1883
        QUEUE_SIZE: 10
        SENSOR_INTERVAL_MS: 8000
        ENABLE_INFOS: 0
    ports:
      - "9092:9090"
    depends_on:
      - postgres
      - thingsboard-ce  
  device_3:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: freertos_mqtt_tago:latest
    container_name: device_3
    environment:
        CLIENT_ID: dev003
        DEVICE_TOKEN: T3_TOKEN
        MQTT_HOST: host.docker.internal
        MQTT_PORT: 1883
        QUEUE_SIZE: 10
        SENSOR_INTERVAL_MS: 10000
        ENABLE_INFOS: 0
    ports:
      - "9093:9090"
    depends_on:
      - postgres
      - thingsboard-ce
  device_4:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: freertos_mqtt_tago:latest
    container_name: device_4
    environment:
        CLIENT_ID: dev004
        DEVICE_TOKEN: T4_TOKEN
        MQTT_HOST: host.docker.internal
        MQTT_PORT: 1883
        QUEUE_SIZE: 10
        SENSOR_INTERVAL_MS: 3000
        ENABLE_INFOS: 0
    ports:
      - "9094:9090"
    depends_on:
      - postgres
      - thingsboard-ce

volumes:
  postgres-data:
    name: tb-postgres-data
    driver: local